### ISSUE TITLE
Resolve functions in values in Helm interface

### ISSUE THREAD

**Issue by skoulouzis** [qcdis-sdia/sdia-deployer#80]
The section values in helm install chart don't resolve values 
```yaml
          install_chart:
            implementation: install_chart.yaml
            inputs:
              repository: https://github.com/QCDIS/helm_playbooks.git
              extra_variables:
                chart_name: metallb/metallb
                repo_name: metallb
                repo_url: 'https://metallb.github.io/metallb'
                helm_name: metallb
                namespace: default
                values:
                  configInline:
                    address-pools:
                     - name: default
                       protocol: layer2
                       addresses:
                        - { get_attribute: [ compute,public_ip ] }
                        - { get_attribute: [ compute_1,public_ip ] }
```
This will carry the { get_attribute: [ compute,public_ip ] } in the deployment
